version: '3'
services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    image: my/app
    volumes:
     - .:/var/www/html
    ports:
     - "80:80"
    networks:
     - appnet
    working_dir: /var/www/html
  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    image: my/node
    volumes:
     - .:/opt
    networks:
     - appnet
    working_dir: /opt
  mysql:
    image: mysql:5.7
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "homestead"
      MYSQL_USER: "homestead"
      MYSQL_PASSWORD: "secret"
    volumes:
     - mysqldata:/var/lib/mysql
    networks:
     - appnet
networks:
  appnet:
    driver: "bridge"
volumes:
  mysqldata:
    driver: "local"